name: XTC MLIR tools and Python bindings wheels build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: &matrixref
        include:
          - {os: ubuntu-24.04, pkg: tools, python: cp310}
          - {os: ubuntu-24.04, pkg: dev, python: cp310}
          - {os: ubuntu-24.04, pkg: python-bindings, python: cp310}
          - {os: ubuntu-24.04, pkg: python-bindings, python: cp311}
          - {os: ubuntu-24.04, pkg: python-bindings, python: cp312}
          - {os: ubuntu-24.04, pkg: python-bindings, python: cp313}
          - {os: ubuntu-24.04, pkg: python-bindings, python: cp314}
          - {os: macos-14, pkg: tools, python: cp310}
          - {os: macos-14, pkg: dev, python: cp310}
          - {os: macos-14, pkg: python-bindings, python: cp310}
          - {os: macos-14, pkg: python-bindings, python: cp311}
          - {os: macos-14, pkg: python-bindings, python: cp312}
          - {os: macos-14, pkg: python-bindings, python: cp313}
          - {os: macos-14, pkg: python-bindings, python: cp314}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: PIP Cache
        uses: actions/cache@v4
        with:
          path: ~/pip_cache
          key: ${{ runner.os }}-pip-cache-${{ matrix.pkg }}-${{ matrix.python }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pip-cache-${{ matrix.pkg }}-${{ matrix.python }}
            ${{ runner.os }}-pip-cache-${{ matrix.pkg }}
            ${{ runner.os }}-pip-cache
      - name: CCache Cache
        uses: actions/cache@v4
        with:
          path: ~/ccache
          key: ${{ runner.os }}-ccache-${{ matrix.pkg }}-${{ matrix.python }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.pkg }}-${{ matrix.python }}
            ${{ runner.os }}-ccache-${{ matrix.pkg }}
            ${{ runner.os }}-ccache
      - name: DNF Cache
        uses: actions/cache@v4
        with:
          path: ~/dnf_cache
          key: ${{ runner.os }}-dnf-cache
      - name: Checkout LLVM
        run: |
          ./checkout-llvm.sh
      - name: Install macOS Brew Packages
        if: runner.os == 'macOS'
        run: |
          brew install ccache
      - name: Instrall cibuildwheel
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Build Wheels
        run: |
          export CIBUILDWHEEL=$PWD/.venv/bin/cibuildwheel
          export BUILD_PIP_CACHE_DIR=$HOME/pip_cache
          export BUILD_CCACHE_DIR=$HOME/ccache
          export BUILD_DNF_CACHE_DIR=$HOME/dnf_cache
          export BUILD_FOR_PYTHON=${{ matrix.python }}
          ./build-wheels-${{ matrix.pkg }}.sh
      - name: Store distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-xtc-mlir-${{ matrix.pkg }}-${{ matrix.python }}-${{ matrix.os }}
          path: wheelhouse/

  publish-to-testpypi:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: *matrixref
    environment:
      name: testpypi
      url: https://test.pypi.org/p/xtc-mlir-${{ matrix.pkg }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-xtc-mlir-${{ matrix.pkg }}-${{ matrix.python }}-${{ matrix.os }}
        path: dist/
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip-existing: true

  publish-to-pypi:
    if: startsWith(github.ref, 'refs/tags/mlir-v')  # only publish to PyPI on tag pushes
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: *matrixref
    environment:
      name: pypi
      url: https://pypi.org/p/xtc-mlir-${{ matrix.pkg }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-xtc-mlir-${{ matrix.pkg }}-${{ matrix.python }}-${{ matrix.os }}
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
